In [10]:
import numpy as np

answer_text = "a d c s b c"
source_text = "f d c a b"

a_words = answer_text.split()
s_words = source_text.split()

a_word_count = len(a_words)
s_word_count = len(s_words)

lcs_matrix = np.zeros((s_word_count + 1, a_word_count + 1), dtype=int)
print(lcs_matrix)

for s, s_word in enumerate(s_words, 1):
    for a, a_word in enumerate(a_words, 1):
        if s_word == a_word:
            lcs_matrix[s][a] = lcs_matrix[s-1][a-1] + 1
        else:
            lcs_matrix[s][a] = max(lcs_matrix[s-1][a], lcs_matrix[s][a-1])

print(lcs_matrix)            
lcs = lcs_matrix[s_word_count][a_word_count]
lcs

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 1 1 1 1]
 [0 0 1 2 2 2 2]
 [0 1 1 2 2 2 2]
 [0 1 1 2 2 3 3]]


3