In [1]:
import numpy as np

In [15]:
b = np.array([[2],[5],[3]])
b

array([[2],
       [5],
       [3]])

In [16]:
a = np.array([[1,2,3], [0,2,1], [1,1,4]])
a

array([[1, 2, 3],
       [0, 2, 1],
       [1, 1, 4]])

In [18]:
x = np.linalg.inv(a) @ b
x

array([[-7.66666667],
       [ 1.33333333],
       [ 2.33333333]])

In [19]:
v1 = np.array([1,2,3])
v2 = np.array([3,5,1])
v3 = np.array([0,0,8])

In [20]:
b = 3*v1
b

array([3, 6, 9])

In [21]:
x = -1*v1 + v2 -.5*v3
x

array([ 2.,  3., -6.])

In [31]:
a = np.array([[2,4],[3,6]])
b = np.array([19,3])

In [32]:
x = np.linalg.inv(a) @ b
x

array([-1.53122387e+17,  7.65611937e+16])

In [33]:
a = np.array([[-1,4],[3,-5]])
b = np.array([10,1])

In [34]:
x = np.linalg.inv(a) @ b
x

array([7.71428571, 4.42857143])

In [35]:
import sympy as sp

In [38]:
B = [[2,-6], [-1,3], [4,-12]]

In [39]:
# guassian limitation
sp.Matrix(B).rref()

(Matrix([
 [1, -3],
 [0,  0],
 [0,  0]]), (0,))

In [40]:
B = [[2,1,1], [0,1,7], [-3,1,2]]

In [41]:
sp.Matrix(B).rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]), (0, 1, 2))

In [48]:
B = [[1,4,-10], [2,1,1], [-1,3,-11]]

In [49]:
sp.Matrix(B).rref()

(Matrix([
 [1, 0,  2],
 [0, 1, -3],
 [0, 0,  0]]), (0, 1))