In [2]:
import numpy as np

In [6]:
A = np.array([[0,1,1], [1,0,1], [1,1,0]])
A

array([[0, 1, 1],
       [1, 0, 1],
       [1, 1, 0]])

In [7]:
B = np.array([[0,2,3], [0,5,0], [7,0,0]]) 
B

array([[0, 2, 3],
       [0, 5, 0],
       [7, 0, 0]])

In [4]:
A@B

array([[7, 5, 0],
       [7, 2, 3],
       [0, 7, 3]])

In [5]:
A + B

array([[0, 3, 4],
       [1, 5, 1],
       [8, 1, 0]])

In [9]:
A.transpose()

array([[0, 1, 1],
       [1, 0, 1],
       [1, 1, 0]])

In [10]:
A[1,:]

array([1, 0, 1])

In [20]:
a = A[:,2]
a

array([1, 1, 0])

In [22]:
b = B[2,:]
b

array([7, 0, 0])

In [23]:
a+b

array([8, 1, 0])

In [37]:
v = np.array([2,4,1])
v

array([2, 4, 1])

In [38]:
u = np.array([1,3,5])
u

array([1, 3, 5])

In [39]:
v.dot(u)

19

In [40]:
print(np.linalg.norm(v,1))
print(np.linalg.norm(v,2))
print(np.linalg.norm(v,3))
print(np.linalg.norm(v,4))
print(np.linalg.norm(v,np.inf))

7.0
4.58257569495584
4.179339196381232
4.064813850824944
4.0


In [41]:
print(np.linalg.norm(u,1))
print(np.linalg.norm(u,2))
print(np.linalg.norm(u,3))
print(np.linalg.norm(u,4))
print(np.linalg.norm(u,np.inf))

9.0
5.916079783099616
5.348481241239363
5.156497997732246
5.0


In [42]:
c = v+u
c

array([3, 7, 6])

In [43]:
print(np.linalg.norm(c,1))
print(np.linalg.norm(c,2))
print(np.linalg.norm(c,3))
print(np.linalg.norm(c,4))
print(np.linalg.norm(c,np.inf))

16.0
9.695359714832659
8.368209391204644
7.839989632806745
7.0
