# import numpy as np

# 1

In [78]:
t = np.array([[0,3,0], [2,1,-1], [-1,1,-2]])
a = np.array([[1,0,0], [0,1,0], [0,0,1]])
b = np.array([[1,-1,1], [0,1,2], [0,0,-1]])

In [79]:
t @ a

array([[ 0,  3,  0],
       [ 2,  1, -1],
       [-1,  1, -2]])

In [80]:
t @ b

array([[ 0,  3,  6],
       [ 2, -1,  5],
       [-1,  2,  3]])

# 2,3

In [65]:
def calculate_mat_det(mat):
    num_of_rows = len(mat)
    num_of_columns = len(mat[0])
    if num_of_rows==2 and num_of_columns==2:
        det = mat[0][0] * mat[1][1] - mat[0][1] * mat[1][0]
    elif num_of_rows==3 and num_of_columns==3:
        det = mat[0][0] * (mat[1][1] * mat[2][2] - mat[1][2] * mat[2][1]) -mat[0][1] * (mat[1][0] * mat[2][2] - mat[1][2] * mat[2][0]) +mat[0][2] * (mat[1][0] * mat[2][1] - mat[1][1] * mat[2][0])
    return det

In [66]:
d2_mat = [[1,7], [1,5]]
calculate_mat_det(d2_mat)

-2

In [67]:
d3_mat = np.array([[1,2,3], [4,5,6], [7,8,9]])
calculate_mat_det(d3_mat)

0

In [68]:
np.linalg.det(d2_mat)

-2.0

In [69]:
np.linalg.det(d3_mat)

-9.51619735392994e-16

# 4

In [71]:
a1 = np.array([[1,1], [1,-1]])
np.linalg.inv(a1)

array([[ 0.5,  0.5],
       [ 0.5, -0.5]])

In [73]:
a2 = np.array([[1,2], [3,5]])
np.linalg.inv(a2)

array([[-5.,  2.],
       [ 3., -1.]])

In [75]:
a3 = np.array([[1,0,1], [0,1,1], [1,1,1]])
np.linalg.inv(a3)

array([[ 0., -1.,  1.],
       [-1.,  0.,  1.],
       [ 1.,  1., -1.]])