In [4]:
import numpy as np
from numpy.linalg import inv, solve, norm, eig

In [14]:
A = np.array([
    [4., -1., -1., 0., 0., 0., 0., 0., 0., 0.],
    [-1., 5., -1., -1., -1., 0., 0., 0., 0., 0.],
    [-1., -1., 5., 0., -1., -1., 0., 0., 0., 0.],
    [0., -1., 0., 5., -1., 0., -1., -1., 0., 0.],
    [0., -1., -1., -1., 6., -1., 0., -1., -1., 0.],
    [0., 0., -1., 0., -1., 5., 0., 0., -1., -1.],
    [0., 0., 0., -1., 0., 0., 4., -1., 0., 0.],
    [0., 0., 0., -1., -1., 0., -1., 5., -1., 0.],
    [0., 0., 0., 0., -1., -1., 0., -1., 5., -1.],
    [0., 0., 0., 0., 0., -1., 0., 0., -1., 4.],
])

b = np.array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])

In [24]:
def jacobi(A, b, tolerance):
    xk_1 = np.zeros_like(b)
    D = np.diag(A)
    #print(D)
    #print(np.diag(D))
    LplusU = A - np.diag(D)
    #print(LplusU)
    
    x_k = (b - (LplusU @ xk_1)) / D
    #print(x_k)
    iter = 0
    while (norm(x_k - xk_1, 2)/norm(x_k, 2)) > tolerance:
        iter += 1
        xk_1 = x_k
        x_k = (b - (LplusU @ xk_1)) / D
        #print(x_k)
     
    print(iter)
    return x_k

print(jacobi(A, b, 1e-8))

69
[0.09019607 0.18039214 0.18039214 0.2980392  0.33333332 0.2980392
 0.45490195 0.52156861 0.52156861 0.45490195]


In [23]:
def siedel(A, b, tolerance):
    xk_1 = np.zeros_like(b) # initial solution (zeros)
    LD = np.tril(A)
    U = A - LD
    #print(LD)
    #print(U)
    LDinv = inv(LD)
    
    x_k = LDinv @ (b - U@xk_1)
    #print(x_k)
    iter = 0
    while (norm(x_k - xk_1, 2)/norm(x_k, 2)) > tolerance:
        iter += 1
        xk_1 = x_k
        x_k = LDinv @ (b - U@xk_1)
        #print(x_k)
        
    #for i in range(N):
     #   x = LDinv @ (b - U@x)
    print(iter)    
    return x_k

siedel(A, b, 1e-8)

37


array([0.09019607, 0.18039215, 0.18039215, 0.29803921, 0.33333333,
       0.29803921, 0.45490196, 0.52156862, 0.52156862, 0.45490196])

#### Gauss-Seidel method converges faster than Jacobi's method 

# Q2

In [21]:
def power_method(A):
    x = np.random.rand(A.shape[0])
    for i in range(100):
        x = (A @ x) / norm(x,2)

    lmbda = ((A@x) / x)[0]
    v = x / lmbda
    return lmbda, v

In [22]:
A = np.array([
    [0., 1., 2.],
    [.5, 0., 0.],
    [0., .25, 0.]])
lamda , v = power_method(A)
print(lamda)
print(v)
l, v = eig(A)
print(l)
print(v)

0.8846461771193157
[0.86227396 0.48735527 0.13772604]
[ 0.88464618+0.j        -0.44232309+0.2948714j -0.44232309-0.2948714j]
[[-0.86227396+0.j          0.69332593+0.j          0.69332593-0.j        ]
 [-0.48735527+0.j         -0.54259608-0.36171765j -0.54259608+0.36171765j]
 [-0.13772604+0.j          0.11796101+0.28307982j  0.11796101-0.28307982j]]


In [23]:
A = np.array([
    [0., 6., 8.],
    [.5, 0., 0.],
    [0., .5, 0.]])
lamda , v = power_method(A)
print(lamda)
print(v)
l, v = eig(A)
print(l)
print(v)

2.0
[0.96836405 0.24209101 0.06052275]
[ 2.         -0.99999998 -1.00000002]
[[-0.96836405  0.87287156 -0.87287156]
 [-0.24209101 -0.43643579  0.43643578]
 [-0.06052275  0.2182179  -0.21821788]]
