# Session 3 - Solving System of Linear Equations

In [1]:
import numpy as np

A = np.array([
    [10., -1., 2., 0.],
    [-1., 11., -1., 3.],
    [2., -1., 10., -1.],
    [0., 3., -1., 8.]
])

b = np.array([6., 25., -11., 15.])

## Jacobi's Method

$$ x^{(k)} = D^{-1}b - D^{-1} (L+U)x^{(k-1)}$$
$$ x^{(k)} = D^{-1}(b - (L+U)x^{(k-1)}) $$

Stop criteria = $||x^{(k)} - x^{(k-1)} || / ||x^{(k)}|| < tolerance$

In [12]:
from numpy.linalg import inv, solve, norm

def jacobi(A, b, tolerance):
    xk_1 = np.zeros_like(b)
    D = np.diag(A)
    #print(D)
    #print(np.diag(D))
    LplusU = A - np.diag(D)
    #print(LplusU)
#     print((b - LplusU @ xk_1) / D)
#     print(np.diag(D) @ (b - (LplusU @ xk_1))
    
    x_k = (b - (LplusU @ xk_1)) / D
    iter = 0
    while (norm(x_k - xk_1, 2)/norm(x_k, 2)) > tolerance:
        iter += 1
        xk_1 = x_k
        x_k = (b - (LplusU @ xk_1)) / D
    
#     for i in range(N):
#         x = (b - LplusU.dot(x)) / D

    print(iter)
    return x_k

print(jacobi(A, b, 1e-8))


8
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Gauss-Siedel Method

In [14]:
from numpy.linalg import inv

def siedel(A, b, N):
    x = np.zeros_like(b) # initial solution (zeros)
    LD = np.tril(A)
    U = A - LD
    #print(LD)
    #print(U)
    LDinv = inv(LD)
    iter = 0
    for i in range(N):
        iter += 1
        x = LDinv @ (b - U@x)
        
    print(iter)    
    return x
    
    

siedel(A, b, 9)

9


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Diagonally Dominant Matrices

In [15]:
np.set_printoptions(precision=4)
N = 10
for f in range(1, 50):
#     f = 0.01
    A = np.eye(N) * f
    A += np.random.rand(N, N)
    b = A @ np.ones(N)

    x = jacobi(A, b, 1e-6)
    #x = siedel(A, b, 9)
    print(x)



C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: RuntimeWarning: invalid value encountered in double_scalars
  from ipykernel import kernelapp as app


336
[3.0725e+153 4.0972e+153 5.2795e+153 4.0369e+153 4.3008e+153 3.7356e+153
 5.8759e+153 4.9776e+153 3.2071e+153 4.1445e+153]
596
[7.0384e+153 6.9705e+153 6.7606e+153 4.7181e+153 5.6690e+153 5.3927e+153
 4.4530e+153 8.1530e+153 6.9415e+153 6.2884e+153]
1116
[3.4637e+153 4.4983e+153 3.1085e+153 3.9651e+153 5.6686e+153 4.2674e+153
 5.0431e+153 6.2265e+153 4.7353e+153 5.3647e+153]
3369
[-5.6221e+153 -5.3682e+153 -4.6261e+153 -3.9811e+153 -4.0521e+153
 -4.5322e+153 -5.1765e+153 -3.4286e+153 -5.0616e+153 -3.8542e+153]
40
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
47
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
33
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
25
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
19
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
17
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
15
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
14
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
13
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
13
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
11
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
11
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
11
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
11
[1. 1. 1. 1. 1. 1. 1. 

## The Power Method

In [21]:
from numpy.linalg import eig

A = np.array([
    [10., -1., 2., 0.],
    [-1., 11., -1., 3.],
    [2., -1., 10., -1.],
    [0., 3., -1., 8.]
])

l, v = eig(A)
print(l)
print(v)

print()

print(A @ v[:, 0])
print(l[0] * v[:, 0])

x = np.random.rand(4)
for i in range(50):
    x = (A @ x) / norm(x,2)

lmbda = ((A@x) / x)[0]
v = x / lmbda
print(lmbda)
print(v)

[14.0735 10.8191  8.1434  5.964 ]
[[ 0.3935 -0.6234 -0.6404 -0.2155]
 [-0.6802 -0.4913  0.2267 -0.4945]
 [ 0.4613 -0.5009  0.7079  0.1877]
 [-0.4119 -0.3451 -0.1934  0.8208]]

[ 5.5376 -9.5729  6.4921 -5.7975]
[ 5.5376 -9.5729  6.4921 -5.7975]
14.07345801634111
[ 0.3935 -0.6802  0.4613 -0.4119]


## The PageRank Algorithm